//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AMoralesRestauranteEntities : DbContext
    {
        public AMoralesRestauranteEntities()
            : base("name=AMoralesRestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Restaurante> Restaurantes { get; set; }
    
        public virtual int RestauranteAdd(string nombre, Nullable<int> capacidad, string eslogan, Nullable<System.DateTime> fechaInaguracion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var esloganParameter = eslogan != null ?
                new ObjectParameter("Eslogan", eslogan) :
                new ObjectParameter("Eslogan", typeof(string));
    
            var fechaInaguracionParameter = fechaInaguracion.HasValue ?
                new ObjectParameter("FechaInaguracion", fechaInaguracion) :
                new ObjectParameter("FechaInaguracion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestauranteAdd", nombreParameter, capacidadParameter, esloganParameter, fechaInaguracionParameter);
        }
    
        public virtual int RestauranteDelete(Nullable<int> idRestaurante)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("IdRestaurante", idRestaurante) :
                new ObjectParameter("IdRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestauranteDelete", idRestauranteParameter);
        }
    
        public virtual ObjectResult<RestauranteGetById_Result> RestauranteGetById(Nullable<int> idRestaurante)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("IdRestaurante", idRestaurante) :
                new ObjectParameter("IdRestaurante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RestauranteGetById_Result>("RestauranteGetById", idRestauranteParameter);
        }
    
        public virtual int RestauranteUpdate(Nullable<int> idRestaurante, string nombre, Nullable<int> capacidad, string eslogan, Nullable<System.DateTime> fechaInaguracion)
        {
            var idRestauranteParameter = idRestaurante.HasValue ?
                new ObjectParameter("IdRestaurante", idRestaurante) :
                new ObjectParameter("IdRestaurante", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var esloganParameter = eslogan != null ?
                new ObjectParameter("Eslogan", eslogan) :
                new ObjectParameter("Eslogan", typeof(string));
    
            var fechaInaguracionParameter = fechaInaguracion.HasValue ?
                new ObjectParameter("FechaInaguracion", fechaInaguracion) :
                new ObjectParameter("FechaInaguracion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestauranteUpdate", idRestauranteParameter, nombreParameter, capacidadParameter, esloganParameter, fechaInaguracionParameter);
        }
    
        public virtual ObjectResult<RestauranteGetAll_Result> RestauranteGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RestauranteGetAll_Result>("RestauranteGetAll");
        }
    }
}
