//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        public int IdRestaurante { get; set; }
        public string Nombre { get; set; }
        public int Capacidad { get; set; }
        public string Eslogan { get; set; }
        public System.DateTime FechaInaguracion { get; set; }
    }
}
